FROM docker.io/nixos/nix@sha256:bbd436fac4b50712fb065c3cb1d74702aa9d731cc6cc702dbba20a9ccb2d8769
#ADD tiny.overlay.nix /etc/nixos/overlays/tiny.nix
#ENV NIX_PATH="$NIX_PATH:nixpkgs-overlays=/etc/nixos/overlays"
# This is big, and hard to eliminate from the closure. Put it in its own layer.
RUN nix-build '<nixpkgs>' -A glibcLocales --no-out-link
RUN nix-env -i \
  -A nixpkgs.backblaze-b2 \
  -A nixpkgs.bc \
  -A nixpkgs.coreutils \
  -A nixpkgs.curl \
  -A nixpkgs.dumb-init \
  -A nixpkgs.file \
  -A nixpkgs.fping \
  -A nixpkgs.fzf \
  -A nixpkgs.gnupg \
  -A nixpkgs.htop \
  -A nixpkgs.iftop \
  -A nixpkgs.iproute \
  -A nixpkgs.iputils \
  -A nixpkgs.jnettop \
  -A nixpkgs.jq \
  -A nixpkgs.kakoune \
  -A nixpkgs.kubectl \
  -A nixpkgs.kubernetes-helm \
  -A nixpkgs.lsof \
  -A nixpkgs.man-pages \
  -A nixpkgs.ncdu \
  -A nixpkgs.nettools \
  -A nixpkgs.nmap \
  -A nixpkgs.pass \
  -A nixpkgs.pbzip2 \
  -A nixpkgs.pigz \
  -A nixpkgs.procps \
  -A nixpkgs.psmisc \
  -A nixpkgs.pv \
  -A nixpkgs.rclone \
  -A nixpkgs.restic \
  -A nixpkgs.ripgrep \
  -A nixpkgs.rsync \
  -A nixpkgs.sysstat \
  -A nixpkgs.talosctl \
  -A nixpkgs.tcpdump \
  -A nixpkgs.terraform \
  -A nixpkgs.tmux \
  -A nixpkgs.tree \
  -A nixpkgs.unzip \
  -A nixpkgs.util-linux \
  -A nixpkgs.wget \
  -A nixpkgs.zip
ENTRYPOINT ["/root/.nix-profile/bin/dumb-init"]
CMD ["/root/.nix-profile/bin/sleep", "infinity"]
WORKDIR /root
