ARG rook_image

FROM $rook_image AS build
USER root
RUN dnf install --assumeyes cargo
ADD crate/Cargo.toml /crate/Cargo.toml
ADD crate/Cargo.lock /crate/Cargo.lock
RUN \
  cd /crate && \
  mkdir src && \
  echo 'fn main() { unreachable!() }' > src/main.rs && \
  cargo build --locked && \
  cargo build --locked --release && \
  rm -rf src && \
  find target | xargs touch -t 197001010000.00
ADD crate/src /crate/src
RUN cd /crate && cargo test --locked && cargo build --locked --release

FROM $rook_image
USER root
RUN dnf install --assumeyes dumb-init && rm -rf /var/cache/dnf
COPY --from=build /crate/target/release/rook-ceph-imperative-config /bin/rook-ceph-imperative-config
ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["/bin/rook-ceph-imperative-config"]
USER ceph
