apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmacct-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: pmacct-test
  template:
    metadata:
      labels:
        app: pmacct-test
    spec:
      containers:
      - name: workload
        image: busybox
        command: [sh, -c, "while true; do wget https://kierdavis.com/ > /dev/null; sleep 1; done"]
      - name: pmacctd
        image: pmacct/pmacctd
        volumeMounts:
        - name: config
          mountPath: /etc/pmacct
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: pmacct-test
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pmacct-test
  namespace: default
data:
  pmacctd.conf: |
    daemonize: false
    sampling_rate: 1
    aggregate: src_host, dst_host, src_port, dst_port, proto
    plugins: nfprobe
    nfprobe_receiver: 192.168.178.4:4739
