apiVersion: batch/v1
kind: Job
metadata:
  name: restore-music
  namespace: personal
  labels:
    app: restore-music
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: restore-music
      annotations:
        kubernetes.io/ingress-bandwidth: 10M  # megabits/second
    spec:
      nodeName: maryam
      restartPolicy: Never
      priorityClassName: best-effort
      volumes:
      - name: dest
        persistentVolumeClaim:
          claimName: media
      - name: gpgkey
        secret:
          secretName: gpg-encryption-key
      containers:
      - name: main
        image: nixos/nix
        command:
        - bash
        - -c
        - 'rm -rf /dest/.nobackup/music && mkdir -p /dest/.nobackup/{cache,tmp,music} && nix-env -i -A nixpkgs.duplicity -A nixpkgs.gnupg23 && gpg --batch --import /gpgkey/publickeys.gpg && gpg --batch --import /gpgkey/secretkey.gpg && echo "trusted-key 0x8139C5FCEDA73ABF" >> ~/.gnupg/gpg.conf && gpg --list-keys && gpg --list-secret-keys && exec duplicity restore --verbosity 6 --archive-dir /dest/.nobackup/cache --tempdir /dest/.nobackup/tmp b2://$B2_ACCOUNT_ID:$B2_ACCOUNT_KEY@redactedbucket/duplicity-0/music-0 /dest/.nobackup/music'
        envFrom:
        - secretRef:
            name: old-backblaze
        - secretRef:
            name: old-duplicity
        volumeMounts:
        - name: dest
          mountPath: /dest
        - name: gpgkey
          mountPath: /gpgkey
        resources:
          requests:
            cpu: 40m
            memory: 150Mi
