FROM alpine:3.19 AS build
RUN \
  apk add curl tar && \
  mkdir -p /src && \
  curl --location --fail 'https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz' \
    | tar --extract --gzip --directory=/src ./bridge ./host-local ./loopback

FROM alpine:3.19
RUN apk add dumb-init
COPY --from=build /src /src
ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["/bin/sh", "-c", "cp -v /src/* /dest/"]
