FROM alpine:3.19 AS build
RUN apk add cargo
ADD crate/Cargo.toml /crate/Cargo.toml
ADD crate/Cargo.lock /crate/Cargo.lock
RUN \
  cd /crate && \
  mkdir src && \
  echo 'fn main() { unreachable!() }' > src/main.rs && \
  cargo build --locked --release && \
  rm -rf src && \
  find target | xargs touch -t 197001010000.00
ADD crate/src /crate/src
RUN cd /crate && cargo build --locked --release

FROM alpine:3.19
RUN apk add dumb-init libgcc
COPY --from=build /crate/target/release/config-writer /bin/config-writer
ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["/bin/config-writer"]
