FROM ghcr.io/paperless-ngx/paperless-ngx@sha256:da0476cea301df8bc8d20739f0e76de1e77d91ad2c9170b45c803468dde19208

# After a thouroughly painful troubleshooting session, I found that this fixes
# the garbled text in the PDF/A files produced from newer Jump paychecks.
#
# The input PDFs use the Arial font without embedding it, and by default
# ghostscript resolves this its builtin Nimbus Sans font, which apparantly sucks.
#
# We'll use Liberation Sans instead. It's installed in the image but we need to
# alter ghostscript's config to direct it towards this font rather than Nimbus.
#
# If we just map Arial (& Bold) but not Helvetica, ghostscript crashes.
# I assume this is something to do with the fact the default config first
# de-aliases Arial to Helvetica and then de-aliases Helvetica to Nimbus Sans.
ADD myfontmap.gs /usr/share/ghostscript/myfontmap.gs
ENV GS_OPTIONS=-sFONTMAP=/usr/share/ghostscript/myfontmap.gs
