{ imageTools }:

imageTools.customise {
  base = imageTools.bases.alpine;
  # top-level: ffmpeg, intel-media-driver, libva-utils
  add = [(imageTools.fetchAPKs (pkgs: with pkgs; [
    alsa-lib
    aom-libs
    brotli-libs
    cjson
    dbus-libs
    ffmpeg
    ffmpeg-libavcodec
    ffmpeg-libavdevice
    ffmpeg-libavfilter
    ffmpeg-libavformat
    ffmpeg-libavutil
    ffmpeg-libpostproc
    ffmpeg-libswresample
    ffmpeg-libswscale
    fontconfig
    freetype
    fribidi
    glib
    glslang-libs
    graphite2
    harfbuzz
    hwdata-pci
    intel-gmmlib
    intel-media-driver
    lame-libs
    lcms2
    libass
    libasyncns
    libblkid
    libbluray
    libbsd
    libbz2
    libdav1d
    libdovi
    libdrm
    libexpat
    libffi
    libflac
    libgcc
    libgomp
    libhwy
    libintl
    libjpeg-turbo
    libjxl
    libltdl
    libmd
    libmount
    libogg
    libopenmpt
    libpciaccess
    libplacebo
    libpng
    libpulse
    librist
    libsharpyuv
    libsndfile
    libsodium
    libsrt
    libssh
    libstdcxx
    libSvtAv1Enc
    libtheora
    libunibreak
    libva
    libva-utils
    libvdpau
    libvorbis
    libvpx
    libwebp
    libwebpmux
    libx11
    libxau
    libxcb
    libxdmcp
    libxext
    libxfixes
    libxml2
    libzmq
    lilv-libs
    mbedtls
    mpg123-libs
    numactl
    onevpl-libs
    opus
    orc
    pcre2
    rav1e-libs
    sdl2
    serd-libs
    shaderc
    sord-libs
    soxr
    speexdsp
    spirv-tools
    sratom
    tdb-libs
    v4l-utils-libs
    vidstab
    vulkan-loader
    wayland-libs-client
    x264-libs
    x265-libs
    xvidcore
    xz-libs
    zimg
    zix-libs
  ]))];
  run = imageTools.installAPKs;
  newLayerHash = "sha256-5LiXl1ubURCXm5yqvbO8sbMKm0Hg0NhFAUoJv517nyI=";
}
