FROM docker.io/nixos/nix@sha256:fd7a5c67d396fe6bddeb9c10779d97541ab3a1b2a9d744df3754a99add4046f1
RUN \
  mkdir -p /run/opengl-driver/lib/dri && \
  ln -sf $(nix-build '<nixpkgs>' -A intel-media-driver --no-out-link)/lib/dri/iHD_drv_video.so /run/opengl-driver/lib/dri/iHD_drv_video.so && \
  nix-env -i -A nixpkgs.ffmpeg-full -A nixpkgs.libva-utils
